import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { InfoScreenTemplate } from '../src/components/InfoScreenTemplate';

export default function TermsScreen() {
  const sections = [
    {
      title: 'Agreement to Terms',
      icon: 'document-text',
      content: [
        'By creating an account or accessing AuraPixels, you agree to comply with and be bound by these Terms & Conditions. If you do not agree to these terms, you may not use our services.',
      ],
    },
    {
      title: 'AI Generation & Creative Rights',
      icon: 'sparkles',
      content: [
        '1. Creative Prompts: You are solely responsible for the prompts you submit. You must not submit prompts that contain illegal, harmful, hateful, or explicit content.',
        '2. Art Ownership: AuraPixels grants you a non-exclusive, royalty-free license to use, download, copy, share, and display the wallpapers generated by you for personal and non-commercial usage.',
        '3. Fair Attribution: When posting generated wallpapers on external media, we appreciate linking back to AuraPixels or attributing the platform, though it is not strictly required.',
      ],
    },
    {
      title: 'User Conduct & Platform Integrity',
      icon: 'alert-circle',
      content: [
        'To keep AuraPixels safe and premium for everyone, you agree NOT to:',
        '• Exploit, scrape, or flood our servers with high-frequency automated requests.',
        '• Reverse engineer any client-side bundle or attempt unauthorized access to our APIs.',
        '• Abuse the AI generation system (e.g. attempting to circumvent style bounds or create malicious images).',
      ],
    },
    {
      title: 'Account Responsibilities',
      icon: 'person-circle',
      content: [
        'You are responsible for safeguarding your account details (password / login OAuth tokens). You agree to notify us immediately of any unauthorized breach or use of your credentials.',
        'We reserve the right to suspend or delete accounts that violate these terms or engage in harmful activities.',
      ],
    },
  ];

  const footer = (
    <View style={styles.footer}>
      <Text style={styles.dateText}>Last Updated: May 18, 2026</Text>
    </View>
  );

  return (
    <InfoScreenTemplate
      title="Terms & Conditions"
      subtitle="Guidelines for our creative community"
      sections={sections}
      footer={footer}
    />
  );
}

const styles = StyleSheet.create({
  footer: {
    paddingVertical: 10,
  },
  dateText: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '550',
  },
});
